### ISSUE TITLE
mod crash

### ISSUE THREAD

**Issue by samhermans** [contariaa/atum#7]
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'mcsrranked' at 'com.mcsrranked.client.MCSRRankedClient'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'mcsrranked' at 'com.mcsrranked.client.MCSRRankedClient'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 8 more
Caused by: java.lang.RuntimeException: Incompatible mod set found! READ THE BELOW LINES!
These Fabric Mods are whitelisted but different version! Make sure to update these!
	atum-2.1+1.16.1.jar [atum]

**Comment by contariaa** [comment]
It seems like MCSR Ranked hasn't whitelisted the newest Atum version yet. Please report this to Ranked, you can downgrade Atum to 2.0 in the meantime.
